trigger: 
 - main

pool:
   vmImage: 'ubuntu-latest'

steps: 
- task: GoTool@0
  inputs:
    version: '1.13.5'
- task: Go@0
  inputs:
    command: 'get'
    arguments: '-d'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
- task: Go@0
  inputs:
    command: 'build'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
- task: CopyFiles@2
  inputs:
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
     artifactName: drop

- task: UseTerraform@1
  displayName: 'Use Terraform'
  inputs:
    provider: 'azurerm'
    terraformVersion: 'latest' # Or your required Terraform version
    workingDirectory: 'Azure/terraform' # Point to your Terraform code directory
    backendType: 'azurerm' # If you're using AzureRM backend
    backendServiceArm: 'your-azure-rm-service-connection' # Replace with your Azure service connection name
    backendAzureRmResourceGroupName: 'your-tfstate-rg' # Replace with your state resource group
    backendAzureRmStorageAccountName: 'your-tfstate-sa' # Replace with your state storage account
    backendAzureRmContainerName: 'tfstate' # Replace with your state container name
    backendAzureRmKey: 'terraform.tfstate' # Replace with your state file name

- script: |
    cd 'tests'
    go test -v -timeout 30m -junitreport reports/
  displayName: 'Run Terratests'

- task: PublishTestResults@2
  displayName: 'Publish Test Results'
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'tests/reports/*.xml'
    searchFolder: '$(System.DefaultWorkingDirectory)'
    publishRunAttachments: true