trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  TEST_DIR: 'Digital Architecture/tests'
  REPORT_DIR: 'Digital Architecture/tests/reports'
  REPORT_FILE: 'junit-report.xml'

steps:
  - task: UseGoVersion@0
    inputs:
      version: '1.21'
      addToPath: true

  - script: |
      go mod tidy
    workingDirectory: '$(TEST_DIR)'
    displayName: 'Get dependencies'

  - script: |
      mkdir -p "$(REPORT_DIR)"
      go test -v ./... -json | go-junit-report > "$(REPORT_DIR)/$(REPORT_FILE)"
    workingDirectory: '$(TEST_DIR)'
    displayName: 'Run Go tests and generate JUnit report'

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '$(REPORT_DIR)/$(REPORT_FILE)'
      failTaskOnFailedTests: true
      testRunTitle: 'Go Unit Tests'
